elixir: 1.5.2
erlang: 20.1.2
environment:
  PG_URL: postgres:postgres@localhost
  MYSQL_URL: root@localhost
deps:
  docker:
    - image: postgres:9.6.6-alpine
      container_name: postgres
      wait:
        port: 5432
    - image: mysql:5.7.20
      container_name: mysql
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      wait:
        port: 3306
